FROM node:16-alpine as builder
WORKDIR /svelte/src/microservices/user-management/frontend
COPY user-management/frontend/ ./
RUN yarn install && yarn build

FROM node:16-alpine as packager
WORKDIR /svelte/src/microservices/user-management/frontend
COPY --from=builder /svelte/src/microservices/user-management/frontend/package.json ./
COPY --from=builder /svelte/src/microservices/user-management/frontend/target/ ./target/
RUN yarn install --production

FROM gcr.io/distroless/nodejs:16
COPY --from=packager /svelte/src/microservices/user-management/frontend/package.json ./
COPY --from=packager /svelte/src/microservices/user-management/frontend/target/ ./target/
COPY --from=packager /svelte/src/microservices/user-management/frontend/node_modules/ ./node_modules/
CMD ["target/index.js"]
