name: User Management (Frontend)
on:
  push:
    paths:
      - "microservices/user-management/frontend/**"
      - ".github/workflows/user-management.frontend.yml"
  pull_request:
    paths:
      - "microservices/user-management/frontend/**"
      - ".github/workflows/user-management.frontend.yml"
jobs:
  UserManagement_Frontend_Check:
    name: User Management - Frontend - Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./microservices/user-management/frontend
        run: yarn install
      - name: Lint user-management frontend
        working-directory: ./microservices/user-management/frontend
        run: yarn lint
      - name: Build user-management frontend
        working-directory: ./microservices/user-management/frontend
        run: yarn build
      - name: Unit test user-management frontend
        working-directory: ./microservices/user-management/frontend
        run: yarn test
      - name: Integration test user-management frontend
        working-directory: ./microservices/user-management/frontend
        run: yarn cypress:run
  UserManagement_Frontend_Deploy:
    name: User Management - Frontend - Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: UserManagement_Frontend_Check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Log in at Heroku
        run: |
          echo "machine api.heroku.com" > $HOME/.netrc
          echo "  login ${{ secrets.HEROKU_USERNAME }}" >> $HOME/.netrc
          echo "  password ${{ secrets.HEROKU_AUTHORIZATION_TOKEN }}" >> $HOME/.netrc
          echo "machine git.heroku.com" >> $HOME/.netrc
          echo "  login ${{ secrets.HEROKU_USERNAME }}" >> $HOME/.netrc
          echo "  password ${{ secrets.HEROKU_AUTHORIZATION_TOKEN }}" >> $HOME/.netrc
      - name: Set environment variables
        run: |
          heroku config:set ALTRED_UM_SUITE_NAME=altred \
            --app ${{ secrets.HEROKU_USER_MANAGEMENT_FRONTEND_NAME }}
          heroku config:set ALTRED_UM_APPLICATION_NAME=User Management \
            --app ${{ secrets.HEROKU_USER_MANAGEMENT_FRONTEND_NAME }}
          heroku config:set ALTRED_UM_FRONTEND_BASE_URL=https://altred-user-management-frntend.herokuapp.com \
            --app ${{ secrets.HEROKU_USER_MANAGEMENT_FRONTEND_NAME }}
      - name: Log in at Heroku container registry
        run: heroku container:login
      - name: Push Docker image to Heroku
        working-directory: ./microservices/user-management/frontend
        run: |
          heroku container:push web \
            --app ${{ secrets.HEROKU_USER_MANAGEMENT_FRONTEND_NAME }} \
            --context-path ../..
      - name: Release on Heroku
        run: heroku container:release --app ${{ secrets.HEROKU_USER_MANAGEMENT_FRONTEND_NAME }} web
