name: User Management (Backend)
on:
  push:
    paths:
      - "microservices/user-management/backend/**"
  pull_request:
    paths:
      - "microservices/user-management/backend/**"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Lint user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path microservices/user-management/backend/Cargo.toml -- --check
      - name: Analyze user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path microservices/user-management/backend/Cargo.toml --all-targets -- -D warnings
      - name: Test user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path microservices/user-management/backend/Cargo.toml
      - name: Build user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path microservices/user-management/backend/Cargo.toml --release
