name: User Management (Backend)
on:
  push:
    paths:
      - "microservices/user-management/backend/**"
      - ".github/workflows/user-management.backend.yml"
  pull_request:
    paths:
      - "microservices/user-management/backend/**"
      - ".github/workflows/user-management.backend.yml"
jobs:
  UserManagement_Backend_Check:
    name: User Management - Backend - Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Lint user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path microservices/user-management/backend/Cargo.toml -- --check
      - name: Analyze user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path microservices/user-management/backend/Cargo.toml --all-targets -- -D warnings -A clippy::map_entry
      - name: Test user-management backend
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path microservices/user-management/backend/Cargo.toml
  UserManagement_Backend_Deploy:
    name: User Management - Backend - Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: UserManagement_Backend_Check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Log in at Heroku
        run: |
          echo "machine api.heroku.com" > $HOME/.netrc
          echo "  login ${{ secrets.HEROKU_USERNAME }}" >> $HOME/.netrc
          echo "  password ${{ secrets.HEROKU_AUTHORIZATION_TOKEN }}" >> $HOME/.netrc
          echo "machine git.heroku.com" >> $HOME/.netrc
          echo "  login ${{ secrets.HEROKU_USERNAME }}" >> $HOME/.netrc
          echo "  password ${{ secrets.HEROKU_AUTHORIZATION_TOKEN }}" >> $HOME/.netrc
      - name: Log in at Heroku container registry
        run: heroku container:login
      - name: Push Docker image to Heroku
        working-directory: ./microservices/user-management/backend
        run: heroku container:push web --app ${{ secrets.HEROKU_USER_MANAGEMENT_BACKEND_NAME }} --arg DATABASE_URL=HEROKU_USER_MANAGEMENT_DB_URL
      - name: Release on Heroku
        run: heroku container:release --app ${{ secrets.HEROKU_USER_MANAGEMENT_BACKEND_NAME }} web
